// Auto-generated by scripts/generate-lesson-index.cjs
// Do not edit manually.
import type { LessonMeta, LessonModule } from "@/features/lessons/model/types";

export const lessonLoaders: Record<string, () => Promise<LessonModule>> = {
  "methods-params-types": () => import("./methods-params-types.mdx"),
  "nestjs-architecture": () => import("./nestjs-architecture.mdx"),
  "nestjs-di": () => import("./nestjs-di.mdx"),
  "welcome": () => import("./welcome.mdx"),
};

export const lessonMeta: Record<string, LessonMeta> = {
  "methods-params-types": {"slug":"methods-params-types","title":"Method Parameters and Type Annotations","description":"Method Parameters and Type Annotations","order":4},
  "nestjs-architecture": {"slug":"nestjs-architecture","title":"NestJS Architecture: How & Why","description":"Modules, controllers, providers, and why Nest looks the way it does.","order":2},
  "nestjs-di": {"slug":"nestjs-di","title":"Dependency Injection in NestJS","description":"Providers, tokens, scopes, and common DI mistakes.","order":3},
  "welcome": {"slug":"welcome","title":"Welcome to NestJS Learning","description":"Overview of the learning path and how to navigate lessons.","order":1},
};

export const lessonSlugs = Object.keys(lessonLoaders);
